### ISSUE TITLE
Template Extrapolate

### ISSUE THREAD

**Issue by ThomasThelen** [wbpark91/FIN514#1]
Fun work!

I saw that last commit and I couldn't help but stop by and say that you've got the *perfect* opportunity to template that 
`double extrapolate(double x1, double y1, double x2, double y2) `
function!

Also, `payoff_` in the options classes is the perfect case for using `std::shared_ptr` or` std::unique_ptr`. Instead of having to worry about deleting the object in the destructor, it is automatically released when the object goes out of scope.

**Comment by wbpark91** [comment]
@ThomasThelen Oh, I just have seen your comments! I'll try to change it.
